export const AUTH_START = 'AUTH_START';
export const AUTH_END = 'AUTH_END';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';

export const CLEAN_UP = 'CLEAN_UP';

export const VERIFY_START = 'VERIFY_START';
export const VERIFY_SUCCESS = 'VERIFY_SUCCESS';
export const VERIFY_FAIL = 'VERIFY_FAIL';

export const RECOVERY_START = 'RECOVERY_START';
export const RECOVERY_SUCCESS = 'RECOVERY_SUCCESS';
export const RECOVERY_FAIL = 'RECOVERY_FAIL';

export const ACCOUNT_EDIT_START = 'ACCOUNT_EDIT_START';
export const ACCOUNT_EDIT_SUCCESS = 'ACCOUNT_EDIT_SUCCESS';
export const ACCOUNT_EDIT_FAIL = 'ACCOUNT_EDIT_FAIL';

export const DELETE_START = 'DELETE_START';
export const DELETE_FAIL = 'DELETE_FAIL';

export const ADD_TODO_START = 'ADD_TODO_START';
export const ADD_TODO_SUCCESS = 'ADD_TODO_SUCCESS';
export const ADD_TODO_FAIL = 'ADD_TODO_FAIL';

export const DELETE_TODO_START = 'DELETE_TODO_START';
export const DELETE_TODO_SUCCESS = 'DELETE_TODO_SUCCESS';
export const DELETE_TODO_FAIL = 'DELETE_TODO_FAIL';

export const SEND_INVITE_START = 'SEND_INVITE_START'
export const SEND_INVITE_SUCCESS = 'SEND_INVITE_SUCCESS'
export const SEND_INVITE_FAIL = 'SEND_INVITE_FAIL'

export const ADD_FRIEND_START = 'ADD_FRIEND_START';
export const ADD_FRIEND_SUCCESS = 'ADD_FRIEND_SUCCESS';
export const ADD_FRIEND_FAIL = 'ADD_FRIEND_FAIL';

export const DELETE_FRIEND_START = 'DELETE_FRIEND_START';
export const DELETE_FRIEND_SUCCESS = 'DELETE_FRIEND_SUCCESS';
export const DELETE_FRIEND_FAIL = 'DELETE_FRIEND_FAIL';

export const BLOCK_FRIEND_START = 'BLOCK_FRIEND_START';
export const BLOCK_FRIEND_SUCCESS = 'BLOCK_FRIEND_SUCCESS';
export const BLOCK_FRIEND_FAIL = 'BLOCK_FRIEND_FAIL';